blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogPostCreateView, BlogPostDeleteView, BlogPostDetailView, BlogPostListView, BlogPostUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogPostListView.as_view(), name="blog"),
    path("new/", BlogPostCreateView.as_view(), name="blog_new"),
    path("<int:pk>/update/", BlogPostUpdateView.as_view(), name="blog_update"),
    path("<int:pk>/delete/", BlogPostDeleteView.as_view(), name="blog_delete"),
    path("<int:pk>/detail/", BlogPostDetailView.as_view(), name="blog_detail"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (
    ContactsView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductUpdateView,
    ProductByCategoryView,
)

app_name = CatalogConfig.name
urlpatterns = [
    path("home/", ProductListView.as_view(), name="home"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("product/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path("product/new/", ProductCreateView.as_view(), name="product_new"),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("category/<str:category_name>/", cache_page(60)(ProductByCategoryView.as_view()), name="products_by_category"),
]

online_store_django/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from online_store_django import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name="Наименование", help_text="Введите наименование категории")
    description = models.TextField(
        verbose_name="Описание", help_text="Введите описание категории", blank=True, null=True
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name="Наименование")
    description = models.TextField(max_length=100, verbose_name="Описание", blank=True, null=True)
    image = models.ImageField(upload_to="products/", verbose_name="Изображение", blank=True, null=True)
    category = models.ForeignKey(
        to=Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        blank=True,
        null=True,
        related_name="products",
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена за покупку",
        blank=True,
        null=True,
    )
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Введите дату создания продукта",
        blank=True,
        null=True,
    )
    updated_at = models.DateField(
        verbose_name="Дата последнего изменения",
        help_text="Введите дату последнего изменения продукта",
        blank=True,
        null=True,
    )
    on_sale = models.BooleanField(default=False, verbose_name="Участвует в акции")
    publication_status = models.BooleanField(default=False, verbose_name="Публикация продукта")
    owner = models.ForeignKey(
        to=User, on_delete=models.SET_NULL, verbose_name="Владелец продукта", blank=True, null=True
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
        ]

    def __str__(self):
        return self.name


class Contacts(models.Model):
    country = models.CharField(max_length=150, verbose_name="Страна", help_text="Введите страну")
    inn = models.CharField(max_length=150, verbose_name="ИНН", help_text="Введите ИНН")
    address = models.CharField(max_length=150, verbose_name="Адрес", help_text="Введите адрес")

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

    def __str__(self):
        return f"{self.country}, {self.inn},{self.address}"

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.constants import FORBIDDEN_WORDS
from catalog.models import Product


class StyleFormMixin:
    fields: dict[str, forms.Field]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите название продукта"})
        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание продукта"}
        )
        self.fields["category"].widget.attrs.update({"class": "form-control"})
        self.fields["price"].widget.attrs.update({"class": "form-control", "placeholder": "Введите цену продукта"})
        self.fields["on_sale"].widget.attrs.update({"class": "form-check-input"})


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "category", "price", "image", "on_sale"]

    def clean_name(self):
        name = self.cleaned_data.get("name")
        name_lower = name.lower()
        for word in FORBIDDEN_WORDS:
            if word in name_lower:
                raise forms.ValidationError("Название содержит запрещенное слово")
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        if description:
            description_lower = description.lower().strip()
            for word in FORBIDDEN_WORDS:
                if word in description_lower:
                    raise forms.ValidationError("Описание содержит запрещенное слово")
        return description

    def clean_image(self):
        image = self.cleaned_data.get("image")
        if image:
            max_size = 5 * 1024 * 1024
            if image.size > max_size:
                raise forms.ValidationError("Размер файла не должен превышать 5MB")
            valid_formats = ["image/jpeg", "image/png"]
            if image.content_type not in valid_formats:
                raise ValidationError("Поддерживаются только файлы JPEG и PNG")
        return image

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DeleteView, DetailView, ListView, TemplateView, UpdateView
from django.views.generic.edit import CreateView

from catalog.forms import ProductForm
from catalog.models import Contacts, Product, Category
from catalog.services import ProductService


class BaseTemplateView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["last_products"] = Product.objects.order_by("-created_at")[:5]
        return context


class ContactsView(View):
    template_name = "contacts.html"

    def get(self, request, *args, **kwargs):
        contact = Contacts.objects.first()
        return render(request, self.template_name, {"contact": contact})

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        message = request.POST.get("message")
        return HttpResponse(f"Спасибо, {name}! Ваше сообщение '{message}' получено.")


class ProductDetailView(DetailView):
    model = Product
    template_name = "product_detail.html"
    context_object_name = "product"


class ProductListView(ListView):
    model = Product
    template_name = "product_list.html"
    context_object_name = "products"
    paginate_by = 4
    ordering = ["id"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context

    def get_queryset(self):
        return ProductService.get_products_from_cache()


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "product_form.html"
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "product_form.html"
    success_url = reverse_lazy("catalog:home")

    def get_success_url(self):
        return reverse("catalog:product_detail", args=[self.kwargs.get("pk")])

    def dispatch(self, request, *args, **kwargs):
        product = self.get_object()
        if product.owner != request.user:
            return HttpResponseForbidden("Вы не владелец подукта.")
        return super().dispatch(request, *args, **kwargs)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "product_confirm_delete.html"
    success_url = reverse_lazy("catalog:home")

    def dispatch(self, request, *args, **kwargs):
        product = Product.objects.get(pk=self.kwargs.get("pk"))
        is_owner = product.owner == request.user
        is_moderator = request.user.groups.filter(name="Модератор продуктов").exists()
        has_permission = request.user.has_perm("catalog.delete_product")
        if not (is_owner or (is_moderator and has_permission)):
            return HttpResponseForbidden("У вас нет прав для удаления продукта.")
        return super().dispatch(request, *args, **kwargs)


class ProductUnpublishView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = "catalog.can_unpublish_product"

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.is_published = False
        product.save()
        return redirect("catalog:product_detail", pk=pk)

    def get(self, request, pk):
        return self.post(request, pk)


class ProductByCategoryView(ListView):
    model = Product
    template_name = "product_list.html"
    context_object_name = "products"
    paginate_by = 4
    ordering = ["id"]

    def get_queryset(self):
        category_name = self.kwargs.get("category_name")
        return ProductService.get_product_list(category_name)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category_name"] = self.kwargs["category_name"]
        context["categories"] = Category.objects.all()
        return context

catalog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Восткреп</title>
     <link href="/static/css/bootstrap.min.css" rel="stylesheet"/>

</head>
<body>
{% include "includes/header.html" %}
  <main class="container my-4">
        {% block content %}
        {% endblock %}
    </main>
{% include "includes/footer.html" %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Восткреп</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
{% include "includes/header.html" %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{ contact.country }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{ contact.inn }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ contact.address }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% include "includes/footer.html" %}
</div>
<script href="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/product_confirm_delete.html
{% extends "base.html" %}

{% block title %}Создать продукт{% endblock %}

{% block content %}
<h2>Удалить товар {{ product.name }}?</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit" class="btn btn-secondary">Удалить</button>
    <a href="/home/" class="btn btn-danger">Отмена</a>
</form>
{% endblock %}

catalog/templates/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container vh-50 d-flex align-items-center justify-content-center">
    <div class="row justify-content-center">
        <div class="col-12">
        <div class="card mb-3 center" style="max-width: 1000px; min-height: 300px;">
          <div class="row g-0">
            <div class="col-md-4">
              {% if product.image %}
                <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="{{ product.name }}">
              {% else %}
                <img src="{% static 'img/default-product.jpg' %}" alt="Нет изображения">
              {% endif %}
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">Категория: {{ product.category }}</p>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text">Цена: {{ product.price }} руб.</p>
                <a href="/home/" class="btn btn-secondary mt-auto">
                        Назад
                </a>
              </div>
            </div>
          </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/product_form.html
{% extends "base.html" %}

{% block title %}Создать продукт{% endblock %}

{% block content %}
<h2>Добавить новый товар</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary">Сохранить</button>
    <a href="/home/" class="btn btn-danger">Отмена</a>
</form>
{% endblock %}

catalog/templates/product_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Восточный крепеж</h1>
    <p class="lead">Широкий ассортимент крепежных изделий</p>
</div>
<div class="pricing-header px-3 py-3 pt-md-4 pb-md-4 mx-auto text-center">
{% if category_name %}
    <h4 class="display-6">Категория: {{ category_name }}</h4>
    <p class="lead">Товары из выбранной категории</p>
{% endif %}
</div>
<div class="pricing-header px-3 py-3 mx-auto text-center">
    <div class="d-flex flex-wrap gap-2 justify-content-center">
        <a href="{% url 'catalog:home' %}"
           class="btn btn-secondary {% if not category_name %}active{% endif %}">
            Все продукты
        </a>
        {% for cat in categories %}
            <a href="{% url "catalog:products_by_category" cat.name %}"
               class="btn btn-outline-secondary {% if category_name == cat.name %}active{% endif %}">
                {{ cat.name }}
            </a>
        {% endfor %}

    </div>
</div>
<div class="container mt-5">
    <div class="row g-4">
        {% for product in products %}
        <div class="col-sm-6 col-md-4 col-lg-3 d-flex">
            <div class="card flex-fill text-center shadow-sm h-100">
                   {% if product.image %}
                      <img src="{{ product.image.url }}" alt="{{ product.name }}">
                   {% else %}
                      <img src="{% static 'img/default-product.jpg' %}" alt="Нет изображения">
                   {% endif %}
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-truncate">{{ product.name }}</h5>
                    <p class="card-text small text-muted" style="min-height: 40px;">
                        {{ product.description|truncatechars:100 }}
                    </p>
                    <div class="d-grid gap-2">
                        <a href="/product/{{ product.id }}/" class="btn btn-secondary mt-auto">
                            Посмотреть товар
                        </a>
                        {% if user.is_authenticated %}
                             {% if product.owner == user %}
                             <a href="/product/{{ product.id }}/update/" class="btn btn-secondary mt-auto">
                             Редактировать
                             </a>
                             {% endif %}
                             {% if perms.catalog.can_unpublish_product %}
                              <a href="/home/" class="btn btn-danger mt-auto">
                                  Отменить публикацию
                              </a>
                             {% endif %}
                             {% if product.owner == user or perms.catalog.delete_product %}
                             <a href="/product/{{ product.id }}/delete/" class="btn btn-danger mt-auto">
                                 Удалить
                             </a>
                             {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
     {% if page_obj.has_other_pages %}
        <nav aria-label="Навигация по страницам" class="mt-5">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">‹</a></li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num == page_obj.number %}
                        <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">›</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
</div>
{% endblock %}

catalog/templates/products_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container vh-50 d-flex align-items-center justify-content-center">
    <div class="row justify-content-center">
        <div class="col-12">
        <div class="card mb-3 center" style="max-width: 1000px; min-height: 300px;">
          <div class="row g-0">
            <div class="col-md-4">
              {% if product.image %}
                <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="{{ product.name }}">
              {% else %}
                <img src="{% static 'img/default-product.jpg' %}" alt="Нет изображения">
              {% endif %}
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">Категория: {{ product.category }}</p>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text">Цена: {{ product.price }} руб.</p>
                <a href="/home/" class="btn btn-secondary mt-auto">
                        Назад
                </a>
              </div>
            </div>
          </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}